### ISSUE TITLE
Bioconductor submission

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/cytoviewer#10]
Hi @lassedochreden 

here are a couple of things that need to be done before Bioc submission:

- [x] Write the vignette
- [x] Expand the `cytoviewer` man page on what the app is doing when providing different inputs
- [x] Write simple unit tests
- [x] Write validity checks

**Comment by lassedochreden** [comment]
Thanks for the feedback @nilseling  - Completed (for now)
