### ISSUE TITLE
Zooming

### ISSUE THREAD

**Issue by lassedochreden** [BodenmillerGroup/cytoviewer#19]
It would be great to improve the use of `svgPanZoom` in a way that user input does not change the zoom position of the image (i.e., when zoomed into a single-cell, we can still adjust `bcg` parameters or marker selection and do **not** need to zoom in again). Will (most likely) need some Java-Script experience. 

Potentially helpful issues/ideas: 
https://github.com/timelyportfolio/svgPanZoom/issues/7 
https://stackoverflow.com/questions/39817784/r-svgpanzoom-customize-size-and-add-locator?noredirect=1#comment66926839_39817784

**Comment by Mark-Ste** [comment]
Maybe my suggestion is not directly related to the zooming issue, but it would be beneficial if the images were displayed not just in the upper part of the browser interface but on the entire screen. Currently, I only see the image in the top half of the screen. With a larger display area, it would also save some zooming steps.
Thanks for the great work, cytoviewer is really helpful for our workflow here.

**Comment by lassedochreden** [comment]
Hi @Mark-Ste, 

thanks a lot for the comment and for trying out `cytoviewer`! 

Regarding your suggestion, I will look into increasing the display area size as well as an implementation of a button to toggle the images "fullscreen" (potentially via [shinyfullscreen](https://github.com/etiennebacher/shinyfullscreen)). 

Will get back to this issue once there are new features.

**Comment by lassedochreden** [comment]
Hi @Mark-Ste, 

we have now adapted the default display area size, which was initially hardcoded and now adjusts depending on the available viewport height. 

Will close this issue for now, but feel free to re-open, if needed. 

Thanks for using `cytoviewer`!

**Comment by Mark-Ste** [comment]
Hi @lassedochreden,

tested it out and works perfectly!
Thanks for the fast implementation.
