### ISSUE TITLE
Custom scale bar

### ISSUE THREAD

**Issue by JohnAbbey98** [BodenmillerGroup/cytoviewer#23]
Great work! I use cytoviewer for MALDI-images with larger pixel sizes, e.g. 5, 20 or 50um. Is it be possible to implement a feature where I can input a custom and the scale bar value is adjusted? Would be great to have my scale bar in microns rather than pixels. Thanks devs!

**Comment by lassedochreden** [comment]
Hi @JohnAbbey98, 

thanks for the nice feedback! Under `General` > `Basic controls` > `Image appearance` you can now adjust the **pixel resolution**, which will change the scale-bar label. For this, please install `cytoviewer` from devel/GitHub now. 

Hope this helps. Let me know what you think. Will close this for now.
